### PR TITLE
Add multi-module configuration support and fix form alignment

### PR DESCRIPTION
**Pull request by mpare**
This fixes the issue that caused conflicts after all libraries have been synchronized on the Pi. I've added a combobox 'Module' in the form that will filter only its libraries to by synchronized, if we keep the combobox empty, it will act as before. I've also fixed the form alignment, if you don't like I could revert and only add the 'Module' combobox.

rpi-plugin-screenshot

### CODE REVIEW

**Comment by asebak** [comment]
Thanks @mpare for the fix, once I get the time, I will try it out.

**Comment by asebak** [comment]
This fixes #62

**Comment by mpare** [comment]
@asebak Any idea when you'll have the time to test it? :)

**Comment by asebak** [comment]
@mpare yeah i was getting my envinroment setup again, hopefully by this weekend :).  Sorry it's been taking so long.

**Comment by asebak** [comment]
looks good, will update somethings and then release it in the store.

**Pull request merged**
